apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpget
spec:
  selector:
    matchLabels:
      run: httpget
  replicas: 1
  template:
    metadata:
      labels:
        run: httpget
    spec:
      containers:
      - name: httpget
        image: alexellis/httpget:0.1.0
        ports:
        - containerPort: 8080
